### ISSUE TITLE
Belum ada endpoint get rating courses secara keseluruhan

### ISSUE THREAD

**Issue by agusdwimilniadi** [Kel-21-Alta/ProfCourse#26]
Ini yang di MVP dimaksud rating courses apakah rating dari setiap user atau juga rating gabungan gitu (rata2) ? Kalo dari rating masing2 user berarti udah ada endoint nya. Tapi kalo satu courses terus di rata2 belom ada

**Comment by wahyunf354** [comment]
Mas mag nge get rating dari user disuatu course itu ada key rating_all gak @agusdwimilniadi
